### ISSUE TITLE
Process Crash when use a debugger "single step" over cpuid instruction

### ISSUE THREAD

**Issue by madkarl** [tandasat/HyperPlatform#39] opened 2016-12-30 17:07 UTC
### Description

when i use a debugger(e.g. OllyDbg) to debug a proces, if i
  first:set a hardware breakpoint in this process
  second:use single step to execute over instruction "cpuid"
the process debuged will crash only execute over cpuid

### Steps to reproduce the problem

1.use ollydbg attach/debug a process with cpuid instruction
2.stop before cpuid instruction
3.set a hardware breakpoint in this process
4.start use single step(F8 in OllyDBG) before cpuid 
5."single step" over "cpuid"

### other

it's will crash every time when i try this
but it will not crash when "single step" instruction like rdtsc

**Comment by tandasat** [comment] 2017-01-07 21:08
I was unable to reproduce the issue with the steps you described. The CPUID instruction executed and set expected register values with step over (F8).

Can you try again, and provide details on test environment and a tested program? 

Here is what I did:
- Tested on 64bit Windows 7 VM, and 64bit Windows 10 real device 
- Used OllyDbg 1.10 and HyperPlatform on master
- Used a 32bit program compiled from this code
```

#include "stdafx.h"
#include <intrin.h>

int main()
{
    int regs[4];
    __debugbreak();
    __cpuid(regs, 0);
    return 0;
}

```

Thank you!

**Comment by tandasat** [comment] 2017-02-03 14:35
Closing it because of no replay for more than 2 weeks, and it was not reproducible on my side. Feel free to reopen this issue with updates.

**Closed by tandasat** 2017-02-03 14:35 UTC
Labels: prio:low, type:bug
