### ISSUE TITLE
CRITICAL_STRUCTURE_CORRUPTION (109) after Windows Update

### ISSUE THREAD

**Issue by Morpheus2711** [tandasat/HyperPlatform#61] opened 2019-03-16 14:24 UTC
Hey,

i am using HyperPlaform, in my project, fine for some month. After the last Windows Updates I started to get this bug from time to time. Kinda stuck debugging it atm. If i can provide you any more information, please give me a short description how.

Executable search path is: 
Windows 10 Kernel Version 17134 MP (16 procs) Free x64
Product: WinNt, suite: TerminalServer SingleUserTS
Built by: 17134.1.amd64fre.rs4_release.180410-1804
Machine Name:
Kernel base = 0xfffff801`8fa16000 PsLoadedModuleList = 0xfffff801`8fdc4150

6: kd> !analyze -v

CRITICAL_STRUCTURE_CORRUPTION (109)

Arguments:
Arg1: a39fcc589d48b820, Reserved
Arg2: b3b6d8deefcac0db, Reserved
Arg3: fffff78000000708, Failure type dependent information
Arg4: 0000000000000000, Type of corrupted region, can be
	0   : A generic data region
	1   : Modification of a function or .pdata
	2   : A processor IDT
	3   : A processor GDT

Debugging Details:
------------------
DUMP_CLASS: 1
DUMP_QUALIFIER: 401
BUILD_VERSION_STRING:  17134.1.amd64fre.rs4_release.180410-1804
DUMP_TYPE:  1
BUGCHECK_P1: a39fcc589d48b820
BUGCHECK_P2: b3b6d8deefcac0db
BUGCHECK_P3: fffff78000000708
BUGCHECK_P4: 0
PG_MISMATCH:  7A933DC1
CPU_COUNT: 10
CPU_MHZ: bb8
CPU_VENDOR:  GenuineIntel
CPU_FAMILY: 6
CPU_MODEL: 3f
CPU_STEPPING: 2
CPU_MICROCODE: 6,3f,2,0 (F,M,S,R)  SIG: 3C'00000000 (cache) 3C'00000000 (init)
DEFAULT_BUCKET_ID:  BAD_STACK_0x109
BUGCHECK_STR:  0x109
PROCESS_NAME:  csrss.exe
CURRENT_IRQL:  2
ANALYSIS_SESSION_HOST: 
ANALYSIS_SESSION_TIME:  03-16-2019
ANALYSIS_VERSION: 10.0.16299.15 amd64fre
STACK_TEXT:  
ffffdf8f`84d01978 00000000`00000000 : 00000000`00000109 a39fcc58`9d48b820 b3b6d8de`efcac0db fffff780`00000708 : nt!KeBugCheckEx
THREAD_SHA1_HASH_MOD_FUNC:  81a83ae0317433a47fcc36991983df3b6e638b71
THREAD_SHA1_HASH_MOD_FUNC_OFFSET:  6e16edd8c7dd677734fdbcd2397a2e35e9fae964
THREAD_SHA1_HASH_MOD:  76cd06466d098060a9eb26e5fd2a25cb1f3fe0a3
SYMBOL_NAME:  ANALYSIS_INCONCLUSIVE
FOLLOWUP_NAME:  MachineOwner
MODULE_NAME: Unknown_Module
IMAGE_NAME:  Unknown_Image
DEBUG_FLR_IMAGE_TIMESTAMP:  0
STACK_COMMAND:  .thread ; .cxr ; kb
BUCKET_ID:  BAD_STACK_0x109
PRIMARY_PROBLEM_CLASS:  BAD_STACK_0x109
FAILURE_BUCKET_ID:  BAD_STACK_0x109
TARGET_TIME:  2019-03-16
OSBUILD:  17134
OSSERVICEPACK:  0
SERVICEPACK_NUMBER: 0
OS_REVISION: 0
SUITE_MASK:  272
PRODUCT_TYPE:  1
OSPLATFORM_TYPE:  x64
OSNAME:  Windows 10
OSEDITION:  Windows 10 WinNt TerminalServer SingleUserTS
OS_LOCALE:  
USER_LCID:  0
OSBUILD_TIMESTAMP:  2019-03-06
BUILDDATESTAMP_STR:  180410-1804
BUILDLAB_STR:  rs4_release
BUILDOSVER_STR:  10.0.17134.1.amd64fre.rs4_release.180410-1804
ANALYSIS_SESSION_ELAPSED_TIME:  11cc
ANALYSIS_SOURCE:  KM
FAILURE_ID_HASH_STRING:  km:bad_stack_0x109
FAILURE_ID_HASH:  {b4d7023a-05c3-49b2-3ea4-6240fe57d90e}

**Comment by tandasat** [comment] 2019-03-16 14:39
Hi, does this reproduce on your system? If not, there is a high chance that the crash is caused by the other software such as out dated anti virus.

Please try to collect memory.dmp files and see what drivers are loaded. There might be other drivers that could be the cause.

**Comment by Morpheus2711** [comment] 2019-03-16 18:11
Hi, thx for the fast answear. Yes i am sure it only happens with the driver loaded. I am watching it for some weeks now. 
I have a full Kernel Memeory Dump. ~3GB 

I am currently uploading it to my server, i will E-Mail you a link where you can download it.

**Comment by tandasat** [comment] 2019-03-16 22:14
Hi, does this reproduce on your end? I have seen an issue due to a bug in the other driver before.

**Comment by Morpheus2711** [comment] 2019-03-17 17:47
Yes it reproduces 5-30 min after loading the driver. I dont have any problem if it is not loaded.

**Comment by Morpheus2711** [comment] 2019-03-18 18:18
I just got it again. Any advise how i can find the cause? I know what 109 means but i have no clue how to find the code doing the bead modification.


BugCheck 109, {a39fdf5a3648ba10, b3b6ebe088cac2cb, fffff78000000708, 0}

fffff80281e53388: Unable to get MiVisibleState
Unable to get NonPagedPoolStart
Unable to get NonPagedPoolEnd
Unable to get PagedPoolStart
Unable to get PagedPoolEnd
GetUlongFromAddress: unable to read from fffff80281da8740
Probably caused by : Unknown_Image ( ANALYSIS_INCONCLUSIVE )

Followup:     MachineOwner
---------

10: kd> !analyze -v


CRITICAL_STRUCTURE_CORRUPTION (109)

Arguments:
Arg1: a39fdf5a3648ba10, Reserved
Arg2: b3b6ebe088cac2cb, Reserved
Arg3: fffff78000000708, Failure type dependent information
Arg4: 0000000000000000, Type of corrupted region, can be

Debugging Details:
------------------

Unable to get NonPagedPoolStart
Unable to get NonPagedPoolEnd
Unable to get PagedPoolStart
Unable to get PagedPoolEnd
GetUlongFromAddress: unable to read from fffff80281da8740
DUMP_CLASS: 1
DUMP_QUALIFIER: 400
BUILD_VERSION_STRING:  10.0.17134.648 (WinBuild.160101.0800)
DUMP_TYPE:  2
DUMP_FILE_ATTRIBUTES: 0x8
  Kernel Generated Triage Dump
BUGCHECK_P1: a39fdf5a3648ba10
BUGCHECK_P2: b3b6ebe088cac2cb
BUGCHECK_P3: fffff78000000708
BUGCHECK_P4: 0
PG_MISMATCH:  6DA374A3
CPU_COUNT: 10
CPU_MHZ: bb8
CPU_VENDOR:  GeuineIntel
CPU_FAMILY: 6
CPU_MODEL: 3f
CPU_STEPPING: 2
CPU_MICROCODE: 6,3f,2,0 (F,M,S,R)  SIG: 3C'00000000 (cache) 3C'00000000 (init)
CUSTOMER_CRASH_COUNT:  1
DEFAULT_BUCKET_ID:  BAD_STACK_0x109
BUGCHECK_STR:  0x109
PROCESS_NAME:  System
CURRENT_IRQL:  2

ANALYSIS_VERSION: 10.0.16299.15 amd64fre

STACK_TEXT:  
fffff98e`73ddf978 00000000`00000000 : 00000000`00000109 a39fdf5a`3648ba10 b3b6ebe0`88cac2cb fffff780`00000708 : nt!KeBugCheckEx

**Comment by tandasat** [comment] 2019-03-19 04:15
If you can reproduce, I sugget disabling vmexit one by one and see if the issue still reproduces with reduced VMM code. You could also test with the latest HyperPlatform. I will prioritize if the issue is in the original code. If not the case, you can still narrow down the cause to newly added code.

**Comment by tandasat** [comment] 2019-03-30 18:26
It seems like someone modified the page where `KUSER_SHARED_DATA` exists. 

```
$$ Decode the 2nd bug check parameter. This magic is hard coded and always same for 109 bug chekck
6: kd> ? b3b6d8deefcac0db - 0xB3B74BDEE4453415 
Evaluate expression: -126443643892538 = ffff8d00`0b858cc6

$$ Dump the structure containing information about a validation range and expected check-sum
6: kd> dq ffff8d00`0b858cc6
ffff8d00`0b858cc6  00000000`00000000 fffff780`00000708
ffff8d00`0b858cd6  27e88e3a`000008f8 00000000`00000000
ffff8d00`0b858ce6  00000000`00000000 00000000`00000000

$$ Dump the range checked by PatchGuard
6: kd> db fffff780`00000708 l000008f8
fffff780`00000708  00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00  ................
...
fffff780`000008f8  00 00 00 00 00 00 00 00-ff 0f 00 a0 3c 49 00 be  ............<I..
fffff780`00000908  ff ff 00 00 00 00 00 00-00 00 00 00 00 00 00 00  ................
```

`fffff780`00000900` has a weird value which appears to be written by some shitty driver.

Closing this issue as it is not an issue of HyperPlatform.

**Closed by tandasat** 2019-03-30 18:26 UTC
